#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Get import files (from backup directory)
#======================================================================================================================

bcg-echo "Importing batch files from /var/lib/backup..."
for FILE in /var/lib/backup/*.sql ; do

    # split out database name from file
    NAME=$(basename -- "${FILE}")
    DATABASE="${NAME%.*}"

    # execute file
    bcg-echo " .. importing '${DATABASE}'"
    mariadb "${DATABASE}" < ${FILE} || bcg-notok " .. something went wrong"

done
bcg-done
