#!/bin/bash

set -euo pipefail


#======================================================================================================================
# Set variables.
#======================================================================================================================

DATE=$(date '+%Y%m%d%H%M')
bf-debug "Backup: ${DATE}."


#======================================================================================================================
# Get databases.
#======================================================================================================================

EXCLUDE="mysql|information_schema|performance_schema|sys"
bf-debug "Exclude ${EXCLUDE}."
DATABASES=$(mariadb --user=root --password=${BF_DB_ROOT_PASSWORD} -e 'SHOW DATABASES;' | sed 1d | grep -v -E "(${EXCLUDE})")
[[ -z "${DATABASES}" ]] && bf-error "No databases found to backup."


#======================================================================================================================
# Dump databases to a temporary folder and compress.
#======================================================================================================================

TEMP_BACKUP_PATH=$(mktemp -d -t backup.XXXXXX) || bf-error "Unable to make temporary backup directory."
bf-echo "Backing up databases to ${TEMP_BACKUP_PATH}..."

for DATABASE in ${DATABASES} ; do

    # path to this database dump
    DUMP_FILE="${TEMP_BACKUP_PATH}/${DATABASE}.sql"
    bf-debug "Dumping to ${DUMP_FILE}."

    # dump database and continue on failure
    bf-echo " .. ${DATABASE}"
    ${BF_DB_LIB}/dump "${DATABASE}" "${DUMP_FILE}" || true

done
bf-done


#======================================================================================================================
# Move backups to backup directory and set permissions.
#======================================================================================================================

BACKUP_PATH=${BF_DB_BACKUP}/${DATE}
bf-echo "Moving backups to ${BACKUP_PATH}..."
mv ${TEMP_BACKUP_PATH} ${BACKUP_PATH}
bf-done


#======================================================================================================================
# Remove old backups.
#======================================================================================================================

if [ "${BF_DB_BACKUP_KEEP_FOR_DAYS}" -gt 0 ] ; then

    bf-echo "Deleting backups older than ${BF_DB_BACKUP_KEEP_FOR_DAYS} days..."
    MMIN=$((60*24*${BF_DB_BACKUP_KEEP_FOR_DAYS}))
    find ${BF_DB_BACKUP}/* -type d -mmin +${MMIN} | xargs rm -rf
    bf-done

fi
