#!/bin/bash

set -euo pipefail


#======================================================================================================================
# Check arguments.
#   1   Database name
#======================================================================================================================

[[ -z "${1-}" ]] && bf-error "You must provide the name of the database to export."
DATABASE=${1}

[[ -z "${2-}" ]] && bf-error "You must provide the path of the dump file."
DUMP_FILE=${2}


#======================================================================================================================
# Dump database to file if it exists.
#======================================================================================================================

[[ ! -d "${MARIADB_DATA}/${DATABASE}" ]] && bf-error "Database '${DATABASE}' does not exist."

mariadb-dump --add-drop-database --user=root --password=${MARIADB_ROOT_PASSWORD} --databases "${DATABASE}" > "${DUMP_FILE}"


#======================================================================================================================
# Compress file.
#======================================================================================================================

[[ "${MARIADB_BACKUP_COMPRESS_FILES}" = "1" ]] && xz -T0 ${DUMP_FILE}
