#!/bin/bash

set -euo pipefail


#======================================================================================================================
# Check arguments.
#   1   Database name
#======================================================================================================================

[[ -z "${1-}" ]] && bf-error "You must provide the name of the database to export."
DATABASE=${1}

[[ ! -d "${MARIADB_DATA}/${DATABASE}" ]] && bf-error "Database '${DATABASE}' does not exist."
EXPORT_FILE="${MARIADB_BACKUP}/${DATABASE}.sql"


#======================================================================================================================
# Dump database to file.
#======================================================================================================================

bf-echo "Exporting database '${DATABASE}' to ${EXPORT_FILE}..."
${MARIADB_LIB}/dump "${DATABASE}" "${EXPORT_FILE}" || bf-error " .. unable to export database '${DATABASE}'."
bf-done
