#!/bin/bash

set -euo pipefail


#======================================================================================================================
# Check arguments.
#   1   Database name
#======================================================================================================================

[[ -z "${1-}" ]] && bf-error "You must provide the name of the database to export."
DATABASE=${1}
EXPORT_FILE="${BF_DB_BACKUP}/${1}.sql"


#======================================================================================================================
# Dump database to file.
#======================================================================================================================

bf-echo "Exporting database '${DATABASE}' to ${EXPORT_FILE}..."
${BF_DB_LIB}/dump "${DATABASE}" "${EXPORT_FILE}" || bf-error " .. unable to export database '${DATABASE}'."
bf-done
