#!/bin/bash

set -euo pipefail
shopt -s nullglob


#======================================================================================================================
# Decompress archives (from backup directory).
#======================================================================================================================

bf-echo "Decompressing archives in ${BF_DB_BACKUP}..."
for FILE in ${BF_DB_BACKUP}/*.sql.bz2 ; do
    bzip2 -df ${FILE}
done
bf-done


#======================================================================================================================
# Import database dump files (from backup directory).
#======================================================================================================================

bf-echo "Importing dump files in ${BF_DB_BACKUP}..."
for FILE in ${BF_DB_BACKUP}/*.sql ; do

    # split out database name from file
    NAME=$(basename -- "${FILE}")
    DATABASE="${NAME%.*}"

    # execute import
    bf-echo " .. importing '${DATABASE}'."
    mariadb --user=root --password=${BF_DB_ROOT_PASSWORD} < ${FILE} \
        || bf-notok "  . something went wrong."

done
bf-done
