#!/bin/bash

set -euo pipefail


#======================================================================================================================
# Get import files (from backup directory).
#======================================================================================================================

EXT="sql"
[[ "${MARIADB_BACKUP_COMPRESS_FILES}" = "1" ]] && EXT="${EXT}.xz"

bf-echo "Importing SQL files from ${MARIADB_BACKUP}..."
for FILE in ${MARIADB_BACKUP}/*.${EXT} ; do

    # split out database name from file
    NAME=$(basename -- "${FILE}")
    DATABASE="${NAME%.*}"

    # execute file
    bf-echo " .. importing '${DATABASE}'."
    mariadb --user=root --password=${MARIADB_ROOT_PASSWORD} "${DATABASE}" < ${FILE} \
        || bf-notok "  . something went wrong."

done
bf-done
