#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Config is re-written every time in case environment variables have been changed
#======================================================================================================================

bcg-echo "Writing MariaDB config..."
esh -o ${MY_CNF} \
    /etc/templates/my.cnf.esh
bcg-done

bcg-echo "Setting MariaDB config permissions to be read-only..."
chown dbadm:dbadm ${MY_CNF}
chmod 0444 ${MY_CNF}
bcg-done
