#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

# library configuration
bf-env "BF_DB_LIB" "${BF_LIB}/mariadb"

# database configuration
BF_DB_CNF=/etc/my.cnf
bf-env "BF_DB_CNF" "${BF_DB_CNF}"

BF_DB_CNF_D=${BF_DB_CNF}.d
bf-env "BF_DB_CNF_D" "${BF_DB_CNF_D}"

BF_DB_DATA=/var/lib/mysql
bf-env "BF_DB_DATA" "${BF_DB_DATA}"
bf-env "BF_DB_BACKUP" "/var/lib/backup"

bf-env "BF_DB_UPGRADE_INFO" "${BF_DB_DATA}/mysql_upgrade_info"

bf-env "BF_DB_ERROR_LOG" "/var/log/mariadb/error.log"

# SSL configuration
if [ "${BF_DB_SSL_ENABLE}" = "1" ] ; then

    BF_DB_SSL=/ssl
    bf-env "BF_DB_SSL" "${BF_DB_SSL}"

    BF_DB_SSL_CNF_D=${BF_DB_CNF_D}/ssl
    bf-env "BF_DB_SSL_CNF_D" "${BF_DB_SSL_CNF_D}"
    bf-env "BF_DB_SSL_CA_KEY" "${BF_DB_SSL_CNF_D}/ca-key.pem"
    bf-env "BF_DB_SSL_CA_CERT" "${BF_DB_SSL_CNF_D}/ca-cert.pem"
    bf-env "BF_DB_SSL_SERVER_KEY" "${BF_DB_SSL_CNF_D}/server-key.pem"
    bf-env "BF_DB_SSL_SERVER_KEY_TMP" "${BF_DB_SSL_CNF_D}/server-key.tmp"
    bf-env "BF_DB_SSL_SERVER_REQ" "${BF_DB_SSL_CNF_D}/server-req.pem"
    bf-env "BF_DB_SSL_SERVER_CERT" "${BF_DB_SSL_CNF_D}/server-cert.pem"
    bf-env "BF_DB_SSL_CLIENT_KEY" "${BF_DB_SSL_CNF_D}/client-key.pem"
    bf-env "BF_DB_SSL_CLIENT_KEY_TMP" "${BF_DB_SSL_CNF_D}/client-key.tmp"
    bf-env "BF_DB_SSL_CLIENT_REQ" "${BF_DB_SSL_CNF_D}/client-req.pem"
    bf-env "BF_DB_SSL_CLIENT_CERT" "${BF_DB_SSL_CNF_D}/client-cert.pem"

fi

# if not defined, set password to match username
if [ -z "${BF_DB_PASSWORD-}" ] ; then
    bf-env "BF_DB_PASSWORD" "${BF_DB_USERNAME-}"
fi
