#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate crontab and append backup task - set the minutes to a random number so multiple containers on one host don't
# all try to backup at the same time.
#======================================================================================================================

bf-echo "Generating crontab..."
CRONTAB=/etc/crontabs/root
bf-esh \
    ${BF_TEMPLATES}/crontab.esh \
    ${CRONTAB}
echo "$((1 + ${RANDOM} % 59)) */8 * * * db-backup" >> /etc/crontabs/root >> ${CRONTAB}
bf-done
