#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Config is re-written every time in case environment variables have been changed
#======================================================================================================================

_echo "Writing MariaDB config..."
gomplate \
    -o /etc/mysql/my.cnf \
    -f /etc/templates/my.cnf.tmpl
_done
