#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Config is re-written every time in case environment variables have been changed
#======================================================================================================================

_echo "Writing MariaDB config..."
esh -o /etc/mysql/my.cnf \
    /etc/templates/my.cnf.tmpl
_done

_echo "Setting MariaDB config permissions..."
chown mysql:mysql /etc/mysql/my.cnf
chmod 0444 /etc/mysql/my.cnf
_done
