#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

# Library configuration
bcg-env "LIB_MARIADB" "${LIB}/mariadb"

# Database configuration
MARIADB_CNF=/etc/my.cnf
bcg-env "MARIADB_CNF" "${MARIADB_CNF}"

MARIADB_CNF_D=${MARIADB_CNF}.d
bcg-env "MARIADB_CNF_D" "${MARIADB_CNF_D}"

bcg-env "MARIADB_DATA_DIR" "/var/lib/mysql"
bcg-env "MARIADB_BACKUP_DIR" "/var/lib/backup"

bcg-env "MARIADB_ERROR_LOG" "/var/log/mariadb/error.log"

# SSL configuration
if [ "${MARIADB_SSL_ENABLE}" = "1" ] ; then
    bcg-env "MARIADB_SSL" "/ssl"
    MARIADB_SSL_CNF_D=${MARIADB_CNF_D}/ssl
    bcg-env "MARIADB_SSL_CNF_D" "${MARIADB_SSL_CNF_D}"
    bcg-env "MARIADB_SSL_CA_KEY" "${MARIADB_SSL_CNF_D}/ca-key.pem"
    bcg-env "MARIADB_SSL_CA_CERT" "${MARIADB_SSL_CNF_D}/ca-cert.pem"
    bcg-env "MARIADB_SSL_SERVER_KEY" "${MARIADB_SSL_CNF_D}/server-key.pem"
    bcg-env "MARIADB_SSL_SERVER_KEY_TMP" "${MARIADB_SSL_CNF_D}/server-key.tmp"
    bcg-env "MARIADB_SSL_SERVER_REQ" "${MARIADB_SSL_CNF_D}/server-req.pem"
    bcg-env "MARIADB_SSL_SERVER_CERT" "${MARIADB_SSL_CNF_D}/server-cert.pem"
    bcg-env "MARIADB_SSL_CLIENT_KEY" "${MARIADB_SSL_CNF_D}/client-key.pem"
    bcg-env "MARIADB_SSL_CLIENT_KEY_TMP" "${MARIADB_SSL_CNF_D}/client-key.tmp"
    bcg-env "MARIADB_SSL_CLIENT_REQ" "${MARIADB_SSL_CNF_D}/client-req.pem"
    bcg-env "MARIADB_SSL_CLIENT_CERT" "${MARIADB_SSL_CNF_D}/client-cert.pem"
fi
