#!/usr/bin/with-contenv bash

if [ -d "/var/lib/mysql/mysql" ] ; then
    echo " - running mariadb-upgrade..."
    mariadb-upgrade --user="root" --password="${MARIADB_ROOT_PASSWORD}" --verbose
    echo " - done."
fi
