#!/command/with-contenv bash

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# If the configuration does not exist, something has gone wrong during initialisation.
#======================================================================================================================

[[ ! -f ${MARIADB_CNF} ]] && bf-error "Configuration file not found."


#======================================================================================================================
# If the mysql directory exists, the server has already been initialised.
#======================================================================================================================

if [ -d ${MARIADB_DATA}/mysql ] ; then

    # start database
    bf-echo "Starting mariadbd-safe."
    mariadbd-safe --user=dbadm


#======================================================================================================================
# Otherwise:
#   - check for root password
#   - check for application username
#   - run server installation
#   - generate initialisation file
#   - run server using initialisation file
#======================================================================================================================

else

    # disable upgrade service
    bf-debug "Database server not installed."
    db-upgrade-disable

    # check for root password
    [[ -z "${MARIADB_ROOT_PASSWORD-}" ]] && bf-error "MARIADB_ROOT_PASSWORD must be set."

    # check for application user
    [[ -z "${MARIADB_USERNAME-}" ]] && bf-error "MARIADB_USERNAME must be set."

    # run server installation
    bf-debug "Running mariadb-install-db..."
    mariadb-install-db --user=dbadm --datadir=${MARIADB_DATA}

    # generate init file
    INIT_FILE=/tmp/init.sql
    bf-debug "Generating initialisation file ${INIT_FILE}..."
    s6-setuidgid dbadm ${MARIADB_LIB}/generate-init-file "${INIT_FILE}"

    # start server with temporary init file
    bf-echo "Starting mariadbd-safe with initialisation file."
    mariadbd-safe --user=dbadm --init-file=${INIT_FILE}

fi
