#!/bin/withenv sh

set -euo pipefail


#======================================================================================================================
# Run preflight checks
#======================================================================================================================

nu -c "use bf-db run ; run preflight"


#======================================================================================================================
# If an init file exists, use it.
#======================================================================================================================

INIT_FILE=$(bf-env DB_INIT_FILE)
if [ -f ${INIT_FILE} ] ; then

    # start server with temporary init file
    bf-write "Starting mariadbd-safe with initialisation file."
    mariadbd-safe --user=dbadm --init-file=${INIT_FILE}

else

    # start database
    bf-write "Starting mariadbd-safe."
    mariadbd-safe --user=dbadm

fi
