#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E="mariadb-log/$(basename ${0})"


#======================================================================================================================
# Forward MariaDB log to Docker.
#======================================================================================================================

bcg-forward mariadb-log ${MARIADB_ERROR_LOG}
