#!/usr/bin/with-contenv bash

echo " - waiting for MariaDB to start..."
s6-svwait /etc/services.d/mariadb

echo " - running mariadb-upgrade..."
mariadb-upgrade --user="root" --password="${MARIADB_ROOT_PASSWORD}"
echo " - done."
