version: "3.8"

services:
  db:
    image: bfren/mariadb:mariadb${MARIADB_VERSION}
    container_name: db
    restart: unless-stopped
    ports:
      - "0.0.0.0:${MARIADB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USERNAME=${MARIADB_USERNAME}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_SSL_ENABLE=1
    volumes:
      - ./v/data:/var/lib/mysql
      - ./v/backup:/var/lib/backup
      - ./v/ssl:/ssl
