version: "3.8"

services:
  db:
    image: bfren/mariadb:mariadb${BF_DB_VERSION}
    container_name: db
    restart: unless-stopped
    ports:
      - "0.0.0.0:${BF_DB_PORT}:3306"
    environment:
      - BF_DB_ROOT_PASSWORD=${BF_DB_ROOT_PASSWORD}
      - BF_DB_USERNAME=${BF_DB_USERNAME}
      - BF_DB_PASSWORD=${BF_DB_PASSWORD}
      - BF_DB_SSL_ENABLE=1
    volumes:
      - ./v/data:/var/lib/mysql
      - ./v/backup:/var/lib/backup
      - ./v/ssl:/ssl
