version: "3.8"

services:
  db:
    image: bfren/mariadb:mariadb${BF_DB_VERSION}
    container_name: db
    restart: unless-stopped
    ports:
      - "${BF_DB_PORT}:3306"
    environment:
      - BF_DB_ROOT_PASSWORD=${BF_DB_ROOT_PASSWORD}
      - BF_DB_USERNAME=${BF_DB_USERNAME}
      - BF_DB_PASSWORD=${BF_DB_PASSWORD}
    volumes:
      - ./v/data:/var/lib/mysql
      - ./v/backup:/var/lib/backup
    networks:
      - app
  # add your app service here

networks:
  app:
    driver: bridge
    name: app
