version: "3.8"

services:
  db:
    image: bfren/mariadb:mariadb${VERSION}
    container_name: db
    restart: unless-stopped
    ports:
      - "${PORT}:3306"
    environment:
      - BF_DB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - BF_DB_APPLICATION=${APPLICATION}
    volumes:
      - ./v/data:/data
      - ./v/backup:/backup
    networks:
      - app
  # add your app service here

networks:
  app:
    driver: bridge
    name: app
