#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Set variables.
#======================================================================================================================

DATE=$(date '+%Y%m%d%H%M')
THIS_BACKUP_PATH=${DB_BACKUP_DIR}/${DATE}


#======================================================================================================================
# Get databases.
#======================================================================================================================

EXCLUDE="mysql|information_schema|performance_schema|sys"
DATABASES=$(mariadb -uroot -p${MARIADB_ROOT_PASSWORD} -e 'SHOW DATABASES;' | sed 1d | grep -v -E "(${EXCLUDE})")
[[ -z "${DATABASES}" ]] && bcg-error "backup: No databases found to backup."


#======================================================================================================================
# Dump databases to a temporary folder and compress.
#======================================================================================================================

TEMP_BACKUP_PATH=$(mktemp -d)

bcg-echo "Backing up databases to ${TEMP_BACKUP_PATH}..."
for DATABASE in ${DATABASES} ; do

    # path to this database dump
    DUMP_FILE="${TEMP_BACKUP_PATH}/${DATABASE}.sql"

    # dump database and continue on failure
    bcg-echo " - ${DATABASE}"
    mariadb-dump --add-locks -uroot -p${MARIADB_ROOT_PASSWORD} ${DATABASE} > ${DUMP_FILE} || true

    ## compress file
    [[ "${DB_BACKUP_COMPRESS_FILES}" = "1" ]] && gzip ${DUMP_FILE}

done
bcg-done


#======================================================================================================================
# Move backups to backup directory and set permissions.
#======================================================================================================================

bcg-echo "Moving backups to ${THIS_BACKUP_PATH}..."
mv ${TEMP_BACKUP_PATH} ${THIS_BACKUP_PATH}
bcg-done

bcg-fix-attrs


#======================================================================================================================
# Remove old backups.
#======================================================================================================================

if [ "${DB_BACKUP_KEEP_FOR_DAYS}" -gt 0 ] ; then

    bcg-echo "Deleting backups older than ${DB_BACKUP_KEEP_FOR_DAYS} days..."
    MMIN=$((60*24*${DB_BACKUP_KEEP_FOR_DAYS}))
    find ${BACKUP_PATH}/* -type d -mmin +${MMIN} | xargs rm -rf
    bcg-done

fi
