#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Check arguments.
#   1   Database name
#======================================================================================================================

[[ -z "${1-}" ]] && bcg-error "You must provide the name of the database to export."

[[ ! -d "${MARIADB_DATA}/${1}" ]] && bcg-error "Database '${1}' does not exist."
EXPORT_FILE="${MARIADB_BACKUP}/${1}.sql"


#======================================================================================================================
# Dump database to file.
#======================================================================================================================

bcg-echo "Exporting database '${1}' to ${EXPORT_FILE}..."
mariadb-dump --add-locks -uroot -p${MARIADB_ROOT_PASSWORD} "${1}" > "${EXPORT_FILE}" \
    || bcg-error " .. unable to export database '${1}'."
bcg-done
