#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Check arguments.
#   1   Database name
#======================================================================================================================

[[ -z "${1-}" ]] && bcg-error "You must provide the name of the database to export."
DATABASE=${1}

[[ ! -d "${MARIADB_DATA}/${DATABASE}" ]] && bcg-error "Database '${DATABASE}' does not exist."
EXPORT_FILE="${MARIADB_BACKUP}/${DATABASE}.sql"


#======================================================================================================================
# Dump database to file.
#======================================================================================================================

bcg-echo "Exporting database '${DATABASE}' to ${EXPORT_FILE}..."
mariadb-dump --add-locks -uroot -p${MARIADB_ROOT_PASSWORD} "${DATABASE}" > "${EXPORT_FILE}" \
    || bcg-error " .. unable to export database '${DATABASE}'."
bcg-done
