#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Config is re-written every time in case environment variables have been changed.
#======================================================================================================================

bcg-echo "Writing MariaDB config..."
esh -o ${DB_CNF} \
    ${TEMPLATES}/my.cnf.esh
bcg-done

bcg-echo "Setting MariaDB config permissions to be read-only..."
chown dbadm:dbadm ${DB_CNF}
chmod 0444 ${DB_CNF}
bcg-done
