#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Get import files (from backup directory).
#======================================================================================================================

bcg-echo "Importing SQL files from ${MARIADB_BACKUP}..."
for FILE in ${MARIADB_BACKUP}/*.sql ; do

    # split out database name from file
    NAME=$(basename -- "${FILE}")
    DATABASE="${NAME%.*}"

    # execute file
    bcg-echo " .. importing '${DATABASE}'."
    mariadb -uroot -p${MARIADB_ROOT_PASSWORD} "${DATABASE}" < ${FILE} \
        || bcg-notok "  . something went wrong."

done
bcg-done
