#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Check if upgrade is necessary
#======================================================================================================================

UPGRADE=${MARIADB_DATA}/mysql_upgrade_info
if [ -f ${UPGRADE} ] ; then

    UPGRADE_VERSION=$(tr -d '\0' < ${UPGRADE}) # remove null byte from mysql_upgrade_info
    bcg-debug "Data version ${UPGRADE_VERSION}."

    THIS_VERSION=$(mariadb --version)
    bcg-debug "Server version ${THIS_VERSION}."

    if [ ${THIS_VERSION} == *"${UPGRADE_VERSION}"* ] ;
        bcg-echo "Data and Server versions match, upgrade not necessary."
        exit 0
    fi

fi


#======================================================================================================================
# Take backup first.
#======================================================================================================================

bcg-debug "Taking backup before running mariadb-upgrade."
db-backup


#======================================================================================================================
# Run mariadb-upgrade as root user.
#======================================================================================================================

bcg-echo "Running mariadb-upgrade..."
mariadb-upgrade -uroot -p${MARIADB_ROOT_PASSWORD}
bcg-done
