#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# If the mysql directory exists, the server has already been initialised
#======================================================================================================================

if [ -d "${DATA_DIR}/mysql" ] ; then

    # start database
    bcg-echo "Starting mariadbd-safe"
    mariadbd-safe --user=dbadm


#======================================================================================================================
# Otherwise:
#   - check for root password
#   - check for application username and password
#   - run server installation
#   - generate initialisation file
#   - run server using initialisation file
#======================================================================================================================

else

    # disable upgrade service
    bcg-echo "Database server not yet installed"
    db-upgrade-disable

    # check for root password
    [[ -z "${MARIADB_ROOT_PASSWORD-}" ]] && bcg-error "MARIADB_ROOT_PASSWORD must be set."

    # check for application user and password
    [[ -z "${MARIADB_USERNAME-}" || -z "${MARIADB_PASSWORD-}" ]] && bcg-error "MARIADB_USERNAME and MARIADB_PASSWORD must be set."

    # run server installation
    bcg-echo "Running mariadb-install-db..."
    mariadb-install-db --user=dbadm --datadir=${DATA_DIR}
    bcg-done

    # generate init file
    INIT_FILE=/tmp/init.sql
    bcg-echo "Generating initialisation file ${INIT_FILE}..."
    s6-setuidgid dbadm /etc/db/generate-init-file "${INIT_FILE}"
    bcg-done

    # start server with temporary init file
    bcg-echo "Starting mariadbd-safe with initialisation file"
    mariadbd-safe --user=dbadm --init-file=${INIT_FILE}

fi
