#!/usr/bin/with-contenv bash

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Old PIDs clog up the mysql directory
#======================================================================================================================

bcg-echo "Clearing temporary files and old process IDs..."
rm -f ${MARIADB_DATA}/*.err
rm -f ${MARIADB_DATA}/*.pid
bcg-done

bcg-clear
