#!/usr/bin/with-contenv bash

set -euo pipefail


#======================================================================================================================
# Old PIDs clog up the mysql directory
#======================================================================================================================

bcg-echo "Cleaning up temporary files and old process IDs..."
rm -rf /tmp/*
rm /var/lib/mysql/*.pid > /dev/null 2>&1
bcg-done
