name: auto-release-arm

on:
  pull_request:
    types: [closed]

jobs:
  create-release-arm:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    -
      name: Create Release ${{ github.event.pull_request.title }}
      uses: bfren/create-release@v2
      with:
        token: ${{ secrets.PAT }}
