name: dev-alpine

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
  build:
    strategy:
      fail-fast: false
      matrix:
        alpine: [ "3.17", "3.18" ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read MariaDB version - minor
        uses: bfren/read-file@v2
        with:
          file: ./alpine${{ matrix.alpine }}/overlay/tmp/MARIADB_MINOR
        id: mariadb_minor
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./alpine${{ matrix.alpine }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: ${{ startsWith(github.ref, 'refs/heads/') }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/mariadb:mariadb${{ steps.mariadb_minor.outpus.contents }}-dev-alpine
            bfren/mariadb:mariadb${{ steps.mariadb_minor.outpus.contents }}-${{ steps.version.outputs.contents }}-beta-alpine
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
